import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {api} from './api';
import {SettingsDialog} from './SettingsDialog';
import './style.css';
import {CodeGeneration, CodeReview} from './CodeGeneration';
import {ProjectCodeReview} from './ProjectCodeReview';
import {ProjectPlanningDialog, ProjectPlanReview} from './ProjectPlanning';
import {ResultsPanel} from './ResultsPanel';
import {WorkflowGraph} from './WorkflowGraph';

const labels = {created:'已创建',running:'执行中',pending:'待执行',succeeded:'已通过',failed:'失败',paused:'已暂停',cancelled:'已取消',needs_attention:'需人工检查',skipped:'已跳过',recorded:'已记录',intent:'等待结果'};
const terminal = ['succeeded','failed','cancelled','needs_attention'];
const pretty = value => JSON.stringify(value,null,2);
function Badge({value}) {return <span className={'badge '+value}>{labels[value] || value}</span>;}
function Json({value}) {return <pre>{typeof value === 'string' ? value : pretty(value)}</pre>;}

// App 管理任务与证据上下文开关。 App manages tasks and the evidence-context option.
function App() {
  const [boot,setBoot]=useState(null), [runs,setRuns]=useState([]), [active,setActive]=useState(null), [id,setId]=useState(''), [detail,setDetail]=useState(null);
  const [error,setError]=useState(''), [busy,setBusy]=useState(false), [online,setOnline]=useState(false), [tab,setTab]=useState('events'), [node,setNode]=useState(''), [inspection,setInspection]=useState(null);
  const [page,setPage]=useState('results');
  const [planning,setPlanning]=useState(false);
  const [generationForm,setGenerationForm]=useState(null);
  const [apis,setApis]=useState(null), [autoAdvance,setAutoAdvance]=useState(true);
  const [composer,setComposer]=useState(false), [parent,setParent]=useState(''), [settings,setSettings]=useState(null);
  const [form,setForm]=useState({repo:'',goal:'验证 Go 项目，运行测试并根据真实工具证据判断结果。',operation:'go_test',pause_after:false,provider:'scripted',full_checks:false});
  useEffect(()=>{api('/bootstrap').then(b=>{setBoot(b);api('/settings').then(setApis).catch(e=>setError(e.message));setForm(f=>({...f,repo:b.default_repo}));}).catch(e=>setError(e.message));},[]);
  useEffect(()=>{let stopped=false,timer; async function poll(){try {const list=await api('/runs'); const data=id?await api('/runs/'+id):null;if(stopped)return;setRuns(list.runs);setActive(list.active_run);setDetail(data);setOnline(true);if(!id&&list.runs.length)setId(list.runs[0].id);}catch(e){if(!stopped){setOnline(false);setError(e.message);}}finally{if(!stopped)timer=setTimeout(poll,1000);}}poll();return()=>{stopped=true;clearTimeout(timer);};},[id]);
  async function act(fn){setBusy(true);setError('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
  function select(rid){setPage('results');setId(rid);setDetail(null);setNode('');setInspection(null);}
  async function start(body=form){setAutoAdvance(!body.pause_after);const r=await api(parent?'/runs/'+parent+'/revise':'/runs',body);select(r.id);setComposer(false);setParent('');}
  function revise(){setParent(id);setForm({repo:detail.run.data.source,goal:detail.run.data.goal,operation:detail.run.data.graph.nodes.find(n=>n.type!=='gate')?.operation || 'go_test',pause_after:false,provider:detail.run.data.model_profile?'live':'scripted',full_checks:detail.run.data.graph.policy_version==='full-verification-v1',role_demo:detail.run.data.graph.policy_version==='readonly-collaboration-v1',intelligence:Boolean(detail.run.data.intelligence)});setComposer(true);}
  async function inspect(ref){const value=await api('/runs/'+id+'/artifacts/'+ref);setInspection({title:'Evidence · '+ref.slice(0,12),value:value.artifact});}
  const run=detail?.run, data=run?.data;
  const events=detail?.events.filter(e=>!node || e.payload.step_id===node || detail.tools.some(t=>t.step_id===node && t.id===e.payload.tool_call_id)) || [];
  const chosen=detail?.steps.find(s=>s.id===node);
  return <div className="shell">
    <aside><a className="brand" href="/">M<span>MASA<small>RUNTIME CONSOLE</small></span></a><button className="primary wide" onClick={()=>{setParent('');setComposer(true);}}>＋ 新建任务</button><div className="side-label">运行记录 <span>{runs.length}</span></div><nav aria-label="运行记录">{runs.map(r=><button key={r.id} className={'run-item '+(id===r.id?'current':'')} onClick={()=>select(r.id)}><span className="run-title">{r.goal}</span><span className="run-meta"><code>{r.id.slice(0,8)}</code><Badge value={r.status}/></span></button>)}</nav><div className="side-foot"><span className={'dot '+(online?'online':'')}/>{online?'本地服务已连接':'正在连接本地服务'}<small>Evidence-driven agent runtime</small></div></aside>
    <main><header><div><div className="eyebrow">需求 → 审核 → 运行 → 结果</div><h1>代码工作台</h1></div><button disabled={!boot?.capabilities.project_planning||!!active} onClick={()=>setPlanning(true)}>规划新项目</button><button className="primary" disabled={!boot?.capabilities.code_generation||!!active} onClick={()=>setGenerationForm({})}>用需求生成代码</button><button onClick={()=>act(async()=>setSettings(await api('/settings')))}>⚙ API 管理</button></header>
    <div className="notice"><strong>{run?.data.codegen?'LLM → 人工审核 → Go 验证':run?.data.model_profile?'Live LLM':'Scripted'}</strong><span>{run?.data.codegen?run.data.codegen.provider.model:run?.data.model_profile?run.data.model_profile.model+' · '+run.data.model_profile.base_url:'Offline verification; select Live LLM when creating a task.'}</span></div>
    {boot&&!boot.capabilities.code_generation&&<div className="error">后端版本过旧，请重启服务后使用代码生成；API 设置遇到问题也请先确认访问的是新服务。</div>}{error&&<div className="error" role="alert">{error}<button onClick={()=>setError('')}>关闭</button></div>}
    {!run?<section className="empty panel"><div className="eyebrow">YOUR FIRST RUN</div><h2>{id?'正在读取运行记录…':'让每一步执行都有迹可循。'}</h2><p>输入目标，运行 Go 工具链，在这里查看图、决策记录与验证证据。</p><button className="primary" disabled={!boot||!!active||busy} onClick={()=>act(()=>start({...form,repo:boot.default_repo}))}>运行 Go 示例 →</button></section>:<>
    <section className="run-heading"><div><div className="eyebrow">RUN / {id.slice(0,12)}</div><h2>{data.goal}</h2><p className="path">{data.source}</p></div><Badge value={run.status}/></section>
    <div className="workspace-toolbar"><div className="tabs">{[['results','运行结果'],['code','代码与审核'],['activity','执行过程']].map(([key,label])=><button key={key} className={page===key?'active':''} onClick={()=>setPage(key)}>{label}{key==='code'&&data.codegen?.status==='awaiting_review'?' · 待批准':''}</button>)}</div><button className="primary" disabled={busy||!!active||!!data.project_plan||!boot?.capabilities.rerun||!['succeeded','failed','needs_attention'].includes(run.status)||(data.codegen&&data.codegen.status!=='approved')} onClick={()=>act(async()=>select((await api('/runs/'+id+'/rerun',{})).id))}>▶ 一键重新验证</button></div>
    {data.codegen?.status==='awaiting_review'&&<div className="notice"><strong>草稿等待你的审核</strong><button onClick={()=>setPage('code')}>查看代码并批准运行 →</button></div>}
    {data.project_plan&&page!=='activity'&&(data.project_plan.kind==='code'?<ProjectCodeReview key={id} detail={detail} select={select}/>:<ProjectPlanReview key={id} detail={detail} profiles={apis} select={select}/>)}
    {page==='results'&&!data.project_plan&&<ResultsPanel detail={detail}/>}
    {page==='code'&&!data.project_plan&&(data.codegen?.proposal_ref?<CodeReview key={id} detail={detail} onRevision={setGenerationForm}/>:<section className="panel"><h3>代码工作区</h3><p className="path">{data.workspace}</p><p>此任务验证已有代码。当前仅生成任务提供在线代码预览；可在本地编辑器查看此文件夹。</p>{data.parent_run_id&&<button onClick={()=>select(data.parent_run_id)}>查看来源任务与代码审核</button>}</section>)}
    {page==='activity'&&<>
    <div className="metrics"><div><small>节点进度</small><strong>{detail.steps.filter(s=>['succeeded','failed','skipped'].includes(s.status)).length}<em> / {detail.steps.length}</em></strong></div><div><small>模型调用</small><strong>{run.model_calls}<em> / {data.budget.model_calls}</em></strong></div><div><small>工具调用</small><strong>{run.tool_calls}<em> / {data.budget.tool_calls}</em></strong></div><div><small>事件记录</small><strong>{detail.event_count}<em> 条</em></strong></div></div>
    <section className="panel"><div className="panel-head"><div><h3>Workflow Graph</h3><small>v{data.graph.version} · {data.graph.policy_version} · 点击节点筛选记录</small></div><div className="actions"><label className="check"><input type="checkbox" checked={autoAdvance} disabled={!!active} onChange={e=>setAutoAdvance(e.target.checked)}/> 继续时自动推进</label><button disabled={busy||!detail.active||detail.pause_requested||run.status!=='running'} onClick={()=>act(()=>api('/runs/'+id+'/pause',{}))}>{detail.pause_requested?'等待节点结束…':'暂停'}</button><button disabled={busy||!!active||!!data.project_plan||!['paused','created','running'].includes(run.status)} onClick={()=>act(()=>api('/runs/'+id+'/resume',{pause_after:!autoAdvance}))}>继续</button><button disabled={busy||terminal.includes(run.status)} onClick={()=>act(()=>api('/runs/'+id+'/cancel',{}))}>取消</button><button disabled={busy||!!active||!['paused',...terminal].includes(run.status)} onClick={revise}>修改需求</button></div></div><WorkflowGraph detail={detail} selected={node} onSelect={setNode}/><div className="graph-foot"><span><i className="dot online"/> 已通过 <i className="dot working"/> 执行中 <i className="dot"/> 待执行</span><span>连线表示依赖，当前串行执行 · 暂停在节点边界生效</span></div></section>
    {(run.reason||detail.worker_error)&&<div className="notice">{detail.worker_error||run.reason}</div>}
    <section className="panel evidence"><div className="tabs">{[['events','执行时间线'],['decisions','Agent 决策'],['tools','工具证据'],['state','运行详情']].map(([key,label])=><button className={tab===key?'active':''} key={key} onClick={()=>setTab(key)}>{label}</button>)}<button className="report" onClick={()=>act(async()=>setInspection({title:'运行报告',value:(await api('/runs/'+id+'/report')).markdown}))}>查看报告 ↗</button></div>
      {node&&<div className="filter">筛选节点：{node}<button onClick={()=>setNode('')}>显示全部 ×</button>{chosen?.result_ref&&<button onClick={()=>act(()=>inspect(chosen.result_ref))}>查看节点结果</button>}</div>}
      {(tab==='events'||tab==='decisions')&&<div className="timeline">{tab==='decisions'&&<p className="hint">展示已记录的模型请求、路由与结构化响应，不代表模型内部思维过程。</p>}{events.filter(e=>tab==='events'||e.type.startsWith('model_')).map(e=><div className="event" key={e.seq}><time>{new Date(e.created*1000).toLocaleTimeString()}</time><div><strong>{e.type}</strong><div className="event-data">{pretty(e.payload)}</div><div className="ref-links">{Object.entries(e.payload).filter(([k,v])=>k.endsWith('_ref')&&typeof v==='string').map(([k,v])=><button key={k} onClick={()=>act(()=>inspect(v))}>{k} ↗</button>)}</div></div><code>#{e.seq}</code></div>)}{events.length===0&&<p className="hint">暂无记录。</p>}<p className="hint">显示最近 {detail.events.length} / {detail.event_count} 条事件。</p></div>}
      {tab==='tools'&&<div className="tool-list">{detail.tools.filter(t=>!node||t.step_id===node).map(t=><article key={t.id}><div><strong>{t.step_id}</strong> <Badge value={t.status}/><p><code>{t.id}</code></p></div><button onClick={()=>act(()=>inspect(t.request_ref))}>工具请求</button><button disabled={!t.result_ref} onClick={()=>act(()=>inspect(t.result_ref))}>stdout / stderr / 结果</button></article>)}{!detail.tools.length&&<p className="hint">工具尚未执行。</p>}</div>}
      {tab==='state'&&<div className="state"><p>Snapshot <code>{data.snapshot_id}</code></p>{data.parent_run_id&&<button onClick={()=>select(data.parent_run_id)}>查看修改前的任务 →</button>}<button onClick={()=>act(()=>inspect(data.manifest_ref))}>文件快照清单</button><Json value={{budget:data.budget,workspace:data.workspace,deadline:new Date(data.deadline_at*1000).toLocaleString(),graph:data.graph,attempts:detail.attempts,capabilities:boot?.capabilities}}/></div>}
    </section></>}</>}
    <footer>MASA / 每一个结论，都能回到证据。<span>LOCAL FIRST · PYTHON + GO</span></footer></main>
    {composer&&<div className="overlay"><section className="modal" role="dialog" aria-modal="true" aria-label="任务需求"><div className="panel-head"><h2>{parent?'修改需求 · 新建关联任务':'创建任务'}</h2><button onClick={()=>setComposer(false)}>关闭</button></div><form onSubmit={e=>{e.preventDefault();act(()=>start());}}><label>执行模型<select value={form.provider || 'scripted'} onChange={e=>setForm({...form,provider:e.target.value,role_demo:false})}><option value="scripted">Scripted · 离线验证</option><option value="live">Live LLM · 真实 API</option></select></label>{form.provider==='live'&&<label>API 配置<select value={form.api_profile_id || apis?.active_id || ''} onChange={e=>setForm({...form,api_profile_id:e.target.value})}><option value="" disabled>请先在 API 设置中添加配置</option>{apis?.profiles?.map(p=><option key={p.id} value={p.id}>{p.name || p.model} · {p.key_configured?'密钥就绪':'缺少密钥'}</option>)}</select></label>}<label className="check"><input type="checkbox" checked={Boolean(form.role_demo)} title="Scripted only; restart the backend to enable" disabled={form.provider==='live'||!boot?.capabilities.readonly_role_protocol} onChange={e=>setForm({...form,role_demo:e.target.checked,full_checks:false})}/> 四角色只读协议演示（Scripted，不修改代码）</label><label className="check"><input type="checkbox" disabled={Boolean(form.role_demo)} checked={Boolean(form.full_checks)} onChange={e=>setForm({...form,full_checks:e.target.checked})}/> 完整验证图：test + vet + format → Gate</label><label>Go 仓库路径<input required value={form.repo} onChange={e=>setForm({...form,repo:e.target.value})}/></label><label>你的需求<textarea required maxLength={16000} rows={5} value={form.goal} onChange={e=>setForm({...form,goal:e.target.value})}/></label><label>验证操作<select value={form.operation} onChange={e=>setForm({...form,operation:e.target.value})}><option value="go_test">go test · 测试</option><option value="go_vet">go vet · 静态检查</option><option value="go_fmt_check">gofmt · 格式检查</option></select></label><label className="check"><input type="checkbox" checked={!form.pause_after} onChange={e=>setForm({...form,pause_after:!e.target.checked})}/> 自动继续执行所有节点并进入 Gate（取消勾选后在首个节点暂停）</label><label className="check"><input type="checkbox" checked={Boolean(form.intelligence)} onChange={e=>setForm({...form,intelligence:e.target.checked})}/> Go AST / 代码证据上下文</label><p className="hint">{parent?'保留原任务和证据，从源仓库重新创建快照；不会覆盖正在执行的图。':'当前 Agent 根据工具证据完成验证；自动规划和代码修复尚未接入。默认总时限 30 分钟，暂停也计入时限。'}</p>{error&&<p className="error" role="alert">{error}</p>}<button className="primary wide" disabled={busy||!!active||!boot?.runner_ready}>{busy?'正在创建…':'启动任务 →'}</button>{active&&<p className="hint">请先暂停或结束当前执行中的任务。</p>}{boot&&!boot.runner_ready&&<p className="error">Go 或 runner 尚未构建，请运行 scripts/build.ps1。</p>}</form></section></div>}
    {planning&&<ProjectPlanningDialog profiles={apis} select={select} close={()=>setPlanning(false)}/>}
    {generationForm&&<CodeGeneration profiles={apis} active={active} initial={generationForm} select={select} close={()=>setGenerationForm(null)}/>}
    {settings&&<SettingsDialog initial={settings} close={()=>setSettings(null)} onUpdate={setApis}/>}
    {inspection&&<div className="overlay"><section className="modal inspector" role="dialog" aria-modal="true" aria-label="证据详情"><div className="panel-head"><h3>{inspection.title}</h3><button onClick={()=>setInspection(null)}>关闭</button></div><Json value={inspection.value}/></section></div>}
  </div>;
}
createRoot(document.getElementById('root')).render(<App/>);
