import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {api} from './api';
import './style.css';

const labels = {created:'已创建',running:'执行中',pending:'待执行',succeeded:'已通过',failed:'失败',paused:'已暂停',cancelled:'已取消',needs_attention:'需人工检查',skipped:'已跳过',recorded:'已记录',intent:'等待结果'};
const terminal = ['succeeded','failed','cancelled','needs_attention'];
const pretty = value => JSON.stringify(value,null,2);
function Badge({value}) {return <span className={'badge '+value}>{labels[value] || value}</span>;}
function Json({value}) {return <pre>{typeof value === 'string' ? value : pretty(value)}</pre>;}

function Graph({detail, selected, onSelect}) {
  const nodes = detail.run.data.graph.nodes;
  const positions = Object.fromEntries(nodes.map((n,i)=>[n.id,{x:40+i*260,y:70}]));
  return <div className="graph-scroll"><div className="graph" style={{width:Math.max(600,nodes.length*260+40)}}>
    <svg width="100%" height="220" aria-label="节点依赖连线"><defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#8ba59f"/></marker></defs>{nodes.flatMap(n=>n.dependencies.map(dep=><path key={dep+n.id} d={'M '+(positions[dep].x+210)+' 112 L '+positions[n.id].x+' 112'} stroke="#8ba59f" strokeWidth="2" markerEnd="url(#arrow)"/>))}</svg>
    {nodes.map((n,i)=>{const step=detail.steps.find(s=>s.id===n.id); return <button key={n.id} className={'node '+(selected===n.id?'selected ':'')+(step?.status || '')} style={{left:positions[n.id].x,top:70}} onClick={()=>onSelect(selected===n.id?'':n.id)}><span className="node-top">{String(i+1).padStart(2,'0')} / {n.type.toUpperCase()} <Badge value={step?.status}/></span><strong>{n.id}</strong><small>{n.type==='gate'?'独立证据验收':n.operation}</small></button>;})}
  </div></div>;
}

// App 管理任务与证据上下文开关。 App manages tasks and the evidence-context option.
function App() {
  const [boot,setBoot]=useState(null), [runs,setRuns]=useState([]), [active,setActive]=useState(null), [id,setId]=useState(''), [detail,setDetail]=useState(null);
  const [error,setError]=useState(''), [busy,setBusy]=useState(false), [online,setOnline]=useState(false), [tab,setTab]=useState('events'), [node,setNode]=useState(''), [inspection,setInspection]=useState(null);
  const [composer,setComposer]=useState(false), [parent,setParent]=useState(''), [settings,setSettings]=useState(null);
  const [form,setForm]=useState({repo:'',goal:'验证 Go 项目，运行测试并根据真实工具证据判断结果。',operation:'go_test',pause_after:true});
  useEffect(()=>{api('/bootstrap').then(b=>{setBoot(b);setForm(f=>({...f,repo:b.default_repo}));}).catch(e=>setError(e.message));},[]);
  useEffect(()=>{let stopped=false,timer; async function poll(){try {const list=await api('/runs'); const data=id?await api('/runs/'+id):null;if(stopped)return;setRuns(list.runs);setActive(list.active_run);setDetail(data);setOnline(true);if(!id&&list.runs.length)setId(list.runs[0].id);}catch(e){if(!stopped){setOnline(false);setError(e.message);}}finally{if(!stopped)timer=setTimeout(poll,1000);}}poll();return()=>{stopped=true;clearTimeout(timer);};},[id]);
  async function act(fn){setBusy(true);setError('');try{await fn();}catch(e){setError(e.message);}finally{setBusy(false);}}
  function select(rid){setId(rid);setDetail(null);setNode('');setInspection(null);}
  async function start(body=form){const r=await api(parent?'/runs/'+parent+'/revise':'/runs',body);select(r.id);setComposer(false);setParent('');}
  function revise(){setParent(id);setForm({repo:detail.run.data.source,goal:detail.run.data.goal,operation:detail.run.data.graph.nodes.find(n=>n.type!=='gate')?.operation || 'go_test',pause_after:true});setComposer(true);}
  async function inspect(ref){const value=await api('/runs/'+id+'/artifacts/'+ref);setInspection({title:'Evidence · '+ref.slice(0,12),value:value.artifact});}
  const run=detail?.run, data=run?.data;
  const events=detail?.events.filter(e=>!node || e.payload.step_id===node || detail.tools.some(t=>t.step_id===node && t.id===e.payload.tool_call_id)) || [];
  const chosen=detail?.steps.find(s=>s.id===node);
  return <div className="shell">
    <aside><a className="brand" href="/">M<span>MASA<small>RUNTIME CONSOLE</small></span></a><button className="primary wide" onClick={()=>{setParent('');setComposer(true);}}>＋ 新建任务</button><div className="side-label">运行记录 <span>{runs.length}</span></div><nav aria-label="运行记录">{runs.map(r=><button key={r.id} className={'run-item '+(id===r.id?'current':'')} onClick={()=>select(r.id)}><span className="run-title">{r.goal}</span><span className="run-meta"><code>{r.id.slice(0,8)}</code><Badge value={r.status}/></span></button>)}</nav><div className="side-foot"><span className={'dot '+(online?'online':'')}/>{online?'本地服务已连接':'正在连接本地服务'}<small>Evidence-driven agent runtime</small></div></aside>
    <main><header><div><div className="eyebrow">WORKSPACE / OBSERVABILITY</div><h1>运行控制台<span className="version">P0</span></h1></div><button onClick={()=>act(async()=>setSettings(await api('/settings')))}>⚙ API 设置</button></header>
    <div className="notice"><strong>Scripted 模式</strong><span>当前执行真实 Go 检查；模型行为为固定脚本。真实 LLM、多 Agent 与代码修复将在后续阶段接入。</span></div>
    {error&&<div className="error" role="alert">{error}<button onClick={()=>setError('')}>关闭</button></div>}
    {!run?<section className="empty panel"><div className="eyebrow">YOUR FIRST RUN</div><h2>{id?'正在读取运行记录…':'让每一步执行都有迹可循。'}</h2><p>输入目标，运行 Go 工具链，在这里查看图、决策记录与验证证据。</p><button className="primary" disabled={!boot||!!active||busy} onClick={()=>act(()=>start({...form,repo:boot.default_repo}))}>运行 Go 示例 →</button></section>:<>
    <section className="run-heading"><div><div className="eyebrow">RUN / {id.slice(0,12)}</div><h2>{data.goal}</h2><p className="path">{data.source}</p></div><Badge value={run.status}/></section>
    <div className="metrics"><div><small>节点进度</small><strong>{detail.steps.filter(s=>['succeeded','failed','skipped'].includes(s.status)).length}<em> / {detail.steps.length}</em></strong></div><div><small>模型调用 · scripted</small><strong>{run.model_calls}<em> / {data.budget.model_calls}</em></strong></div><div><small>工具调用</small><strong>{run.tool_calls}<em> / {data.budget.tool_calls}</em></strong></div><div><small>事件记录</small><strong>{detail.event_count}<em> 条</em></strong></div></div>
    <section className="panel"><div className="panel-head"><div><h3>Workflow Graph</h3><small>v{data.graph.version} · {data.graph.policy_version} · 点击节点筛选记录</small></div><div className="actions"><button disabled={busy||!detail.active||detail.pause_requested||run.status!=='running'} onClick={()=>act(()=>api('/runs/'+id+'/pause',{}))}>{detail.pause_requested?'等待节点结束…':'暂停'}</button><button disabled={busy||!!active||!['paused','created','running'].includes(run.status)} onClick={()=>act(()=>api('/runs/'+id+'/resume',{}))}>继续</button><button disabled={busy||terminal.includes(run.status)} onClick={()=>act(()=>api('/runs/'+id+'/cancel',{}))}>取消</button><button disabled={busy||!!active||!['paused',...terminal].includes(run.status)} onClick={revise}>修改需求</button></div></div><Graph detail={detail} selected={node} onSelect={setNode}/><div className="graph-foot"><span><i className="dot online"/> 已通过 <i className="dot working"/> 执行中 <i className="dot"/> 待执行</span><span>暂停在节点边界生效 · 工具输出完成后入库</span></div></section>
    {(run.reason||detail.worker_error)&&<div className="notice">{detail.worker_error||run.reason}</div>}
    <section className="panel evidence"><div className="tabs">{[['events','执行时间线'],['decisions','Agent 决策'],['tools','工具证据'],['state','运行详情']].map(([key,label])=><button className={tab===key?'active':''} key={key} onClick={()=>setTab(key)}>{label}</button>)}<button className="report" onClick={()=>act(async()=>setInspection({title:'运行报告',value:(await api('/runs/'+id+'/report')).markdown}))}>查看报告 ↗</button></div>
      {node&&<div className="filter">筛选节点：{node}<button onClick={()=>setNode('')}>显示全部 ×</button>{chosen?.result_ref&&<button onClick={()=>act(()=>inspect(chosen.result_ref))}>查看节点结果</button>}</div>}
      {(tab==='events'||tab==='decisions')&&<div className="timeline">{tab==='decisions'&&<p className="hint">展示已记录的模型请求、路由与结构化响应，不代表模型内部思维过程。</p>}{events.filter(e=>tab==='events'||e.type.startsWith('model_')).map(e=><div className="event" key={e.seq}><time>{new Date(e.created*1000).toLocaleTimeString()}</time><div><strong>{e.type}</strong><div className="event-data">{pretty(e.payload)}</div><div className="ref-links">{Object.entries(e.payload).filter(([k,v])=>k.endsWith('_ref')&&typeof v==='string').map(([k,v])=><button key={k} onClick={()=>act(()=>inspect(v))}>{k} ↗</button>)}</div></div><code>#{e.seq}</code></div>)}{events.length===0&&<p className="hint">暂无记录。</p>}<p className="hint">显示最近 {detail.events.length} / {detail.event_count} 条事件。</p></div>}
      {tab==='tools'&&<div className="tool-list">{detail.tools.filter(t=>!node||t.step_id===node).map(t=><article key={t.id}><div><strong>{t.step_id}</strong> <Badge value={t.status}/><p><code>{t.id}</code></p></div><button onClick={()=>act(()=>inspect(t.request_ref))}>工具请求</button><button disabled={!t.result_ref} onClick={()=>act(()=>inspect(t.result_ref))}>stdout / stderr / 结果</button></article>)}{!detail.tools.length&&<p className="hint">工具尚未执行。</p>}</div>}
      {tab==='state'&&<div className="state"><p>Snapshot <code>{data.snapshot_id}</code></p>{data.parent_run_id&&<button onClick={()=>select(data.parent_run_id)}>查看修改前的任务 →</button>}<button onClick={()=>act(()=>inspect(data.manifest_ref))}>文件快照清单</button><Json value={{budget:data.budget,workspace:data.workspace,deadline:new Date(data.deadline_at*1000).toLocaleString(),graph:data.graph,attempts:detail.attempts,capabilities:boot?.capabilities}}/></div>}
    </section></>}
    <footer>MASA / 每一个结论，都能回到证据。<span>LOCAL FIRST · PYTHON + GO</span></footer></main>
    {composer&&<div className="overlay"><section className="modal" role="dialog" aria-modal="true" aria-label="任务需求"><div className="panel-head"><h2>{parent?'修改需求 · 新建关联任务':'创建任务'}</h2><button onClick={()=>setComposer(false)}>关闭</button></div><form onSubmit={e=>{e.preventDefault();act(()=>start());}}><label>Go 仓库路径<input required value={form.repo} onChange={e=>setForm({...form,repo:e.target.value})}/></label><label>你的需求<textarea required maxLength={16000} rows={5} value={form.goal} onChange={e=>setForm({...form,goal:e.target.value})}/></label><label>验证操作<select value={form.operation} onChange={e=>setForm({...form,operation:e.target.value})}><option value="go_test">go test · 测试</option><option value="go_vet">go vet · 静态检查</option><option value="go_fmt_check">gofmt · 格式检查</option></select></label><label className="check"><input type="checkbox" checked={form.pause_after} onChange={e=>setForm({...form,pause_after:e.target.checked})}/> 验证节点结束后暂停，由我确认后继续 Gate</label><label className="check"><input type="checkbox" checked={Boolean(form.intelligence)} onChange={e=>setForm({...form,intelligence:e.target.checked})}/> Go AST / 代码证据上下文</label><p className="hint">{parent?'保留原任务和证据，从源仓库重新创建快照；不会覆盖正在执行的图。':'P0 记录需求并执行所选检查，尚不根据自然语言生成代码。默认总时限 30 分钟，暂停也计入时限。'}</p>{error&&<p className="error" role="alert">{error}</p>}<button className="primary wide" disabled={busy||!!active||!boot?.runner_ready}>{busy?'正在创建…':'启动任务 →'}</button>{active&&<p className="hint">请先暂停或结束当前执行中的任务。</p>}{boot&&!boot.runner_ready&&<p className="error">Go 或 runner 尚未构建，请运行 scripts/build.ps1。</p>}</form></section></div>}
    {settings&&<SettingsDialog initial={settings} busy={busy} error={error} close={()=>setSettings(null)} save={body=>act(async()=>{setSettings(await api('/settings',body));})}/>}
    {inspection&&<div className="overlay"><section className="modal inspector" role="dialog" aria-modal="true" aria-label="证据详情"><div className="panel-head"><h3>{inspection.title}</h3><button onClick={()=>setInspection(null)}>关闭</button></div><Json value={inspection.value}/></section></div>}
  </div>;
}
function SettingsDialog({initial,busy,error,close,save}) {
 const [values,setValues]=useState({...initial,api_key:''});
 return <div className="overlay"><section className="modal" role="dialog" aria-modal="true" aria-label="API 设置"><div className="panel-head"><h2>模型 API 配置</h2><button onClick={close}>关闭</button></div><div className="notice">配置入口已就绪；P0 执行仍使用 scripted provider，尚不会调用此 API。</div><form onSubmit={e=>{e.preventDefault();save(values);setValues({...values,api_key:''});}}>{[['name','配置名称'],['base_url','Base URL'],['model','模型名称'],['api_key','API Key']].map(([key,label])=><label key={key}>{label}<input type={key==='api_key'?'password':'text'} autoComplete="off" value={values[key]} onChange={e=>setValues({...values,[key]:e.target.value})} placeholder={key==='api_key'?'输入后仅保留在服务端内存':''}/></label>)}<p className="hint">密钥状态：{initial.key_configured?'本次服务会话已配置':'未配置'}。密钥不写入磁盘，重启服务后需重新输入；留空保留已有密钥。名称、URL、模型会保存。</p>{error&&<p className="error" role="alert">{error}</p>}<div className="actions"><button type="submit" className="primary" disabled={busy}>保存配置</button><button type="button" disabled={busy} onClick={()=>save({...values,api_key:'',clear_key:true})}>清除密钥</button></div></form></section></div>;
}
createRoot(document.getElementById('root')).render(<App/>);
